soc: qcom: Fix up a redefiniton error of `START_TRIGGER`
-Caused by a recent Upstream.

include/linux/soc/qcom/geni-se.h:149:9: error: 'START_TRIGGER' macro redefined [-Werror,-Wmacro-redefined]
  149 | #define START_TRIGGER                   BIT(0)
      |         ^
../include/linux/soc/qcom/geni-se.h:121:9: note: previous definition is here
  121 | #define START_TRIGGER                   (BIT(0))